<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Eventos historicos y Análisis de Supervivencia</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Estadística para el Análisis Político 2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inicio</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unidad 1
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="sesion1.html">Modelo Lineal</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unidad 2
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="sesion2.html">Regresión De Poisson</a>
    </li>
    <li>
      <a href="sesion3.html">Regresión Logistica Binaria</a>
    </li>
    <li>
      <a href="sesion6.html">Eventos históricos</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unidad 3
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="sesion4.html">Clusters</a>
    </li>
    <li>
      <a href="sesion5.html">Análisis Factorial</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Extras
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="sesion7.html">Organización de datos</a>
    </li>
    <li>
      <a href="sesion8.html">Juntar bases de datos</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Eventos historicos y Análisis de
Supervivencia</h1>

</div>


<center>
<img src=" " width="200"/>
</center>
<p><strong>FACULTAD DE CIENCIAS SOCIALES - PUCP</strong><br></p>
<div
id="curso-pol-304---estadística-para-el-análisis-político-2-semestre-2025---1"
class="section level2">
<h2>Curso: POL 304 - Estadística para el análisis político 2 | Semestre
2025 - 1 <br></h2>
</div>
<div id="docente-marylia-cruz" class="section level2">
<h2>Docente: Marylia Cruz <br></h2>
<hr />
<p><br></p>
</div>
<div
id="para-qué-sirve-los-eventos-históricos-y-el-análisis-de-supervivencia"
class="section level2">
<h2><strong>🎯 ¿Para qué sirve los Eventos históricos y el Análisis de
Supervivencia?</strong></h2>
<p><br></p>
<p>Para estudiar el tiempo que transcurre hasta que ocurre un evento
específico (muerte, abandono, recaída, cambio de empleo, etc.) y
analizar los factores que influyen en ese tiempo.</p>
<p><br></p>
<p><strong>Concepto clave:</strong></p>
<ul>
<li><p><strong>Evento histórico:</strong> suceso de interés cuya
ocurrencia es registrada a lo largo del tiempo (ej.: muerte, recaída,
abandono escolar, divorcio, cambio de empleo).</p></li>
<li><p><strong>Variable clave:</strong> tiempo hasta el evento (tiempo
de seguimiento o de permanencia).</p></li>
<li><p>Importante: el evento puede no observarse para todos los casos ➤
aparece la censura.</p></li>
</ul>
<p></br></p>
<ul>
<li><p><strong>Tipos de censura</strong></p></li>
<li><ol style="list-style-type: decimal">
<li>Censura a la derecha (la más común)</li>
</ol></li>
</ul>
<p>Sabemos que el evento no ocurrió durante el tiempo de observación,
pero no sabemos si o cuándo ocurrirá después.</p>
<p>📌 Ejemplos:</p>
<p>Un paciente sigue vivo al finalizar el estudio. Una persona no ha
abandonado su trabajo al cierre de la encuesta. Un usuario no cancela su
suscripción durante el periodo de seguimiento.</p>
<p>🔁 Interpretación: sabemos que el tiempo al evento es mayor que el
observado.</p>
<ul>
<li><ol start="2" style="list-style-type: decimal">
<li>Censura a la izquierda</li>
</ol></li>
</ul>
<p>El evento ya había ocurrido antes de que comenzara el seguimiento,
pero no sabemos exactamente cuándo.</p>
<p>📌 Ejemplos:</p>
<p>Encuestamos a personas sobre edad al primer empleo, pero algunas ya
estaban trabajando antes del periodo estudiado, sin recordar la edad
exacta. En un estudio de enfermedades crónicas, algunos participantes ya
tenían la enfermedad al ingresar al estudio, pero no se conoce el
momento exacto del diagnóstico.</p>
<p>🔁 Interpretación: sabemos que el tiempo al evento es menor que el
registrado.</p>
<ul>
<li><ol start="3" style="list-style-type: decimal">
<li>Censura intervalada</li>
</ol></li>
</ul>
<p>No conocemos la fecha exacta del evento, pero sabemos que ocurrió
dentro de un intervalo de tiempo.</p>
<p>📌 Ejemplos:</p>
<p>Un paciente realiza chequeos médicos anuales y en uno de ellos
aparece la enfermedad, pero no sabemos cuándo exactamente surgió entre
chequeos. Una mujer realiza un test de embarazo mensual. El test da
negativo en enero y positivo en febrero: el evento (embarazo) ocurrió
entre ambos meses.</p>
<p>🔁 Interpretación: sabemos que el evento ocurrió entre dos tiempos
conocidos.</p>
</div>
<div id="ejemplos" class="section level1">
<h1><strong>Ejemplos </strong></h1>
<table>
<colgroup>
<col width="22%" />
<col width="17%" />
<col width="9%" />
<col width="17%" />
<col width="12%" />
<col width="21%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Caso.de.Estudio</th>
<th align="left">Evento.de.Interés</th>
<th align="left">Unidad.de.Análisis</th>
<th align="left">Variable.de.Tiempo</th>
<th align="left">Censura</th>
<th align="left">Covariables.Posibles</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Caída de regímenes democráticos</td>
<td align="left">Quiebre del régimen democrático</td>
<td align="left">País-año</td>
<td align="left">Años desde transición democrática</td>
<td align="left">Democracias aún vigentes</td>
<td align="left">PBI per cápita, fragmentación, desigualdad</td>
</tr>
<tr class="even">
<td align="left">Firma de tratados de paz en guerras civiles</td>
<td align="left">Firma del tratado de paz</td>
<td align="left">Conflicto armado</td>
<td align="left">Años desde inicio del conflicto</td>
<td align="left">Conflictos aún activos</td>
<td align="left">Intervención externa, intensidad</td>
</tr>
<tr class="odd">
<td align="left">Estabilidad de coaliciones</td>
<td align="left">Disolución de la coalición</td>
<td align="left">Coalición</td>
<td align="left">Meses desde formación</td>
<td align="left">Coaliciones aún vigentes</td>
<td align="left">Ideología, liderazgo, crisis económica</td>
</tr>
<tr class="even">
<td align="left">Transición democrática</td>
<td align="left">Democratización formal del régimen</td>
<td align="left">País</td>
<td align="left">Años bajo régimen autoritario</td>
<td align="left">Países aún autoritarios</td>
<td align="left">Protestas, presión internacional</td>
</tr>
<tr class="odd">
<td align="left">Permanencia en alianzas</td>
<td align="left">Salida de la alianza</td>
<td align="left">País-alianza</td>
<td align="left">Años desde entrada a la alianza</td>
<td align="left">Países aún miembros</td>
<td align="left">Cambio de liderazgo, amenazas externas</td>
</tr>
</tbody>
</table>
<p></br></p>
</div>
<div id="análisis-kaplan-meier" class="section level1">
<h1><strong>📈 ANÁLISIS KAPLAN-MEIER</strong></h1>
<p></br></p>
<div id="para-qué-sirve" class="section level2">
<h2><strong>✅ ¿Para qué sirve?</strong></h2>
<p>Estimar la probabilidad de “sobrevivir” más allá de cierto tiempo.
Comparar grupos de personas (por ejemplo, hombres vs. mujeres) en
términos de duración hasta el evento.</p>
<p></br></p>
</div>
<div id="cómo-funciona" class="section level2">
<h2><strong>⚙️ ¿Cómo funciona?</strong></h2>
<p>Divide el tiempo en intervalos donde ocurren eventos. Calcula la
probabilidad de sobrevivir en cada intervalo. Maneja correctamente casos
censurados (personas que no llegaron al evento durante el
seguimiento).</p>
<p></br></p>
</div>
<div id="fórmula-del-estimador-de-kaplan-meier" class="section level2">
<h2>Fórmula del Estimador de Kaplan-Meier</h2>
<p>El estimador de Kaplan-Meier se define como:</p>
<p><span class="math display">\[
\hat{S}(t) = \prod_{t_i \leq t} \left( 1 - \frac{d_i}{n_i} \right)
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(\hat{S}(t)\)</span> es la probabilidad
estimada de sobrevivir más allá del tiempo <span
class="math inline">\(t\)</span>,</li>
<li><span class="math inline">\(t_i\)</span> son los tiempos en los que
ocurre al menos un evento,</li>
<li><span class="math inline">\(d_i\)</span> es el número de eventos
(por ejemplo, muertes) ocurridos en el tiempo <span
class="math inline">\(t_i\)</span>,</li>
<li><span class="math inline">\(n_i\)</span> es el número de individuos
en riesgo justo antes de <span class="math inline">\(t_i\)</span>.</li>
</ul>
<p></br></p>
</div>
<div id="cuándo-usarla" class="section level2">
<h2><strong>📅 ¿Cuándo usarla?</strong></h2>
<p>Cuando queremos describir la duración hasta un evento. Comparar
curvas de supervivencia entre grupos sin ajustar por otras
variables.</p>
</div>
</div>
<div id="cómo-se-realiza" class="section level1">
<h1><strong>🛠 ¿Cómo se realiza?</strong></h1>
Usar datos que incluyan: Tiempo de seguimiento. Evento (1 = ocurrió, 0 =
censurado). Grupo (si hay comparación).
</style>
</div>
<div id="modelo-de-regresión-de-cox" class="section level1">
<h1><strong>MODELO DE REGRESIÓN DE COX</strong></h1>
<div id="para-qué-sirve-1" class="section level2">
<h2><strong>✅ ¿Para qué sirve?</strong></h2>
<p>Evaluar el efecto de varias variables sobre el tiempo al evento.
Calcular riesgos relativos (hazard ratios) ajustados. No requiere asumir
una forma específica de la función de supervivencia.</p>
</div>
<div id="cómo-funciona-1" class="section level2">
<h2><strong>⚙️ ¿Cómo funciona?</strong></h2>
<p>Estima cómo las variables (edad, sexo, tratamiento…) afectan la razón
de riesgo. Utiliza una función de riesgo basal no especificada y
coeficientes exponenciales. Supone que las razones de riesgo son
constantes en el tiempo (proporcionalidad de riesgos).</p>
</div>
<div id="cuándo-usarla-1" class="section level2">
<h2><strong>📅 ¿Cuándo usarla?</strong></h2>
<p>Cuando se quiere hacer un análisis multivariado del tiempo hasta el
evento. Ideal si hay variables continuas y categóricas. Cuando se
necesita ajustar por confusores.</p>
</div>
<div id="cómo-se-realiza-1" class="section level2">
<h2><strong>🛠 ¿Cómo se realiza?</strong></h2>
<p>Base con: Tiempo. Evento (1/0). Covariables (edad, sexo, etc.).</p>
</div>
<div id="modelo-de-regresión-de-cox-1" class="section level2">
<h2>Modelo de Regresión de Cox</h2>
<p>El modelo de Cox, o modelo de riesgos proporcionales, se expresa
como:</p>
<p><span class="math display">\[
h(t | X) = h_0(t) \cdot \exp(\beta_1 X_1 + \beta_2 X_2 + \cdots +
\beta_p X_p)
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(h(t | X)\)</span> es la función de
riesgo en el tiempo <span class="math inline">\(t\)</span> dado el
vector de covariables <span class="math inline">\(X\)</span>,</li>
<li><span class="math inline">\(h_0(t)\)</span> es la <strong>función de
riesgo basal</strong> (baseline hazard), no especificada
paramétricamente,</li>
<li><span class="math inline">\(\beta_1, \beta_2, \dots,
\beta_p\)</span> son los coeficientes estimados para las covariables
<span class="math inline">\(X_1, X_2, \dots, X_p\)</span>,</li>
<li><span class="math inline">\(\exp(\beta_j)\)</span> se interpreta
como el <strong>hazard ratio</strong> asociado a la covariable <span
class="math inline">\(X_j\)</span>.</li>
</ul>
<p>Este modelo permite estimar el efecto de las covariables sobre la
razón de riesgo sin hacer suposiciones sobre la forma funcional de <span
class="math inline">\(h_0(t)\)</span>, lo cual lo hace
<strong>semiparamétrico</strong>.</p>
<ul>
<li>Si <span class="math inline">\(\exp(\beta_j) &gt; 1\)</span>: mayor
riesgo de ocurrencia del evento asociado a un aumento en <span
class="math inline">\(X_j\)</span>,</li>
<li>Si <span class="math inline">\(\exp(\beta_j) &lt; 1\)</span>: efecto
protector o menor riesgo,</li>
<li>El modelo asume <strong>proporcionalidad de riesgos</strong>, es
decir, que los efectos de las covariables no cambian en el tiempo.</li>
</ul>
</div>
<div id="cómo-se-realiza-en-r-el-análisis-de-eventos-historicos"
class="section level2">
<h2>¿Cómo se realiza en R el análisis de eventos historicos?**</h2>
</div>
<div id="ejemplo" class="section level2">
<h2>Ejemplo:</h2>
<p>Aunque la base ovarian tiene un origen clínico (cáncer de ovario),
podemos usarla como una base para aprender análisis de eventos
históricos (supervivencia).</p>
<ul>
<li>Cada paciente representa una “institución pública” observada a lo
largo del tiempo. El evento de interés es “el colapso de la operación
institucional” (similar a una falla del tratamiento). Queremos saber
cuánto tiempo permanecen activas y si las decisiones iniciales (como el
tipo de intervención recibida) afectan su duración activa.</li>
</ul>
<pre class="r"><code># Paso 1: Cargar librerías necesarias
library(survival)
library(survminer)</code></pre>
<pre><code>## Loading required package: ggpubr</code></pre>
<pre><code>## 
## Attaching package: &#39;survminer&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:survival&#39;:
## 
##     myeloma</code></pre>
<pre class="r"><code># Cargar base de datos
data(&quot;ovarian&quot;)</code></pre>
<pre><code>## Warning in data(&quot;ovarian&quot;): data set &#39;ovarian&#39; not found</code></pre>
<pre class="r"><code>head(ovarian)</code></pre>
<pre><code>##   futime fustat     age resid.ds rx ecog.ps
## 1     59      1 72.3315        2  1       1
## 2    115      1 74.4932        2  1       1
## 3    156      1 66.4658        2  1       2
## 4    421      0 53.3644        2  2       1
## 5    431      1 50.3397        2  1       1
## 6    448      0 56.4301        1  1       2</code></pre>
<ul>
<li>futime Tiempo hasta evento o censura (días)</li>
<li>fustat Estado: 1 = evento ocurrió, 0 = censurado</li>
<li>rx Tipo de tratamiento recibido (1 o 2)</li>
<li>age Edad de la paciente</li>
</ul>
</div>
</div>
<div
id="el-tipo-de-tratamiento-recibido-afecta-la-duración-de-funcionamiento-institucional-supervivencia"
class="section level1">
<h1>¿El tipo de tratamiento recibido afecta la duración de
funcionamiento institucional (supervivencia)?</h1>
<pre class="r"><code>library(survival)
library(survminer)

data(&quot;ovarian&quot;)</code></pre>
<pre><code>## Warning in data(&quot;ovarian&quot;): data set &#39;ovarian&#39; not found</code></pre>
<pre class="r"><code>names(ovarian)</code></pre>
<pre><code>## [1] &quot;futime&quot;   &quot;fustat&quot;   &quot;age&quot;      &quot;resid.ds&quot; &quot;rx&quot;       &quot;ecog.ps&quot;</code></pre>
</div>
<div id="definimos-el-modelo" class="section level1">
<h1>Definimos el modelo</h1>
<pre class="r"><code>km_modelo=survfit(Surv(futime,fustat)~rx,data=ovarian)
summary(km_modelo)</code></pre>
<pre><code>## Call: survfit(formula = Surv(futime, fustat) ~ rx, data = ovarian)
## 
##                 rx=1 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##    59     13       1    0.923  0.0739        0.789        1.000
##   115     12       1    0.846  0.1001        0.671        1.000
##   156     11       1    0.769  0.1169        0.571        1.000
##   268     10       1    0.692  0.1280        0.482        0.995
##   329      9       1    0.615  0.1349        0.400        0.946
##   431      8       1    0.538  0.1383        0.326        0.891
##   638      5       1    0.431  0.1467        0.221        0.840
## 
##                 rx=2 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##   353     13       1    0.923  0.0739        0.789        1.000
##   365     12       1    0.846  0.1001        0.671        1.000
##   464      9       1    0.752  0.1256        0.542        1.000
##   475      8       1    0.658  0.1407        0.433        1.000
##   563      7       1    0.564  0.1488        0.336        0.946</code></pre>
<ul>
<li><p>A los 59 días, 13 personas seguían en seguimiento, y ocurrió 1
evento (falla). La probabilidad estimada de supervivencia hasta ese
momento fue 92.3%.</p></li>
<li><p>A los 115 días, el número de personas en riesgo era 12, y ocurrió
otro evento. La probabilidad acumulada de seguir “viva” (sin evento)
bajó a 84.6%</p></li>
</ul>
</div>
<div id="gráfico" class="section level1">
<h1>Gráfico</h1>
<pre class="r"><code>ggsurvplot(km_modelo,
           data=ovarian,
           conf.int = TRUE,
           pval = TRUE,
           legend.labs=c(&quot;Tratamiento 1&quot;,&quot;Tramiento 2&quot;),
           xlab=&quot;Días&quot;,
           ylab=&quot;Probabilidad de supervivencia&quot;,
           title=&quot;Curva de Kaplan-Meier según tratamiento&quot;)</code></pre>
<p><img src="sesion6_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<ul>
<li><p>Puedes comparar qué grupo tiene una caída más rápida, lo que
indica menor supervivencia</p></li>
<li><p>Puedes mirar el p-valor del test de log-rank en el gráfico
(ggsurvplot(…, pval = TRUE)):</p></li>
<li><p>Si p &lt; 0.05, hay diferencias estadísticamente significativas
entre los grupos.</p></li>
<li><p>Curvas que descienden más lentamente indican mayor duración /
supervivencia.</p></li>
<li><p>Curvas que caen rápido = mayor frecuencia de eventos (muertes,
fallas, renuncias, etc.).</p></li>
</ul>
</div>
<div id="qué-es-el-test-de-log-rank" class="section level1">
<h1>¿Qué es el test de log-rank?</h1>
<p>Es una prueba no paramétrica que compara si hay diferencias
significativas en la supervivencia entre dos o más grupos a lo largo del
tiempo.</p>
<ul>
<li>H₀ (nula): Las curvas de supervivencia no presentan diferencias
significativas en todos los grupos.</li>
</ul>
</div>
<div id="regreion-de-cox" class="section level1">
<h1>Regreion de Cox</h1>
<p>Estima el efecto de una o más covariables sobre el hazard (tasa de
riesgo) de ocurrencia del evento a lo largo del tiempo.</p>
<ul>
<li>La fórmula general es:</li>
</ul>
<pre class="r"><code>cox_model=coxph(Surv(futime,fustat)~rx+age,data=ovarian)
summary(cox_model)</code></pre>
<pre><code>## Call:
## coxph(formula = Surv(futime, fustat) ~ rx + age, data = ovarian)
## 
##   n= 26, number of events= 12 
## 
##         coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## rx  -0.80397   0.44755  0.63205 -1.272  0.20337   
## age  0.14733   1.15873  0.04615  3.193  0.00141 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##     exp(coef) exp(-coef) lower .95 upper .95
## rx     0.4475      2.234    0.1297     1.545
## age    1.1587      0.863    1.0585     1.268
## 
## Concordance= 0.798  (se = 0.076 )
## Likelihood ratio test= 15.89  on 2 df,   p=4e-04
## Wald test            = 13.47  on 2 df,   p=0.001
## Score (logrank) test = 18.56  on 2 df,   p=9e-05</code></pre>
<ul>
<li><p>Estimamos el efecto del tipo de tratamiento y de la edad sobre el
riesgo de colapso institucional.</p></li>
<li><p>El hazard ratio de rx indica si un tratamiento acelera o retrasa
el evento, controlando por la edad.</p></li>
</ul>
<p>Si el HR de rx es &lt; 1, entonces el tratamiento 2 reduce el riesgo
de colapso, prolongando la duración operativa.</p>
<p>Si el HR &gt; 1, el tratamiento 2 acelera el evento, indicando menor
supervivencia.</p>
<p>Si el p-valor &lt; 0.05, la diferencia es estadísticamente
significativa.</p>
<ul>
<li>rx : tratamiento (expo del coeficiente 0.44)</li>
</ul>
<p>Las personas que recibieron el tratamiento rx=2 tiene un 56% menos de
riesgo de que ocurra el evento en comparación con el grupo rx=1</p>
<ul>
<li>edad = ( expo coeficiente 1.158)</li>
</ul>
<p>Por cada año adicional de edad, el riesgo de que ocurra el evento
aumenta en 15.8%, manteniendo constante el resto de los factores
(independiente del tratamiento)</p>
</div>
<div id="visualización" class="section level1">
<h1>Visualización</h1>
<p>Esto genera un forest plot con los hazard ratios y sus intervalos de
confianza.</p>
<pre class="r"><code>library(survminer)
ggforest(cox_model,data=ovarian)</code></pre>
<p><img src="sesion6_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<ul>
<li>Una línea vertical en HR = 1: esta es la línea de no efecto.</li>
</ul>
<p>Cada variable del modelo tiene:</p>
<ul>
<li>Un punto (el HR estimado),</li>
<li>Una barra horizontal (intervalo de confianza al 95%)</li>
</ul>
<div
id="interpretación-del-hazard-ratio-hr-en-gráficos-tipo-forest-plot"
class="section level2">
<h2>Interpretación del Hazard Ratio (HR) en gráficos tipo Forest
Plot</h2>
<table>
<colgroup>
<col width="40%" />
<col width="59%" />
</colgroup>
<thead>
<tr class="header">
<th>Posición del HR con respecto a 1</th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HR a la derecha de 1</td>
<td>Aumenta el riesgo (<strong>HR &gt; 1</strong>)</td>
</tr>
<tr class="even">
<td>HR a la izquierda de 1</td>
<td>Disminuye el riesgo (<strong>HR &lt; 1</strong>, efecto
protector)</td>
</tr>
<tr class="odd">
<td>Intervalo de confianza cruza el 1</td>
<td>No significativo (<strong>p &gt; 0.05</strong>)</td>
</tr>
<tr class="even">
<td>Intervalo de confianza fuera del 1</td>
<td>Efecto estadísticamente significativo (<strong>p &lt;
0.05</strong>)</td>
</tr>
</tbody>
</table>
<p><a href=""> <button>Descargar la base de datos</button> </a></p>
<p><br></br> <a href="#beginning">Go to page beginning</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
